export const actionTypes = {
  SET_LANG: 'SET_LANG',
  GET_FOOTER_DATA: 'GET_FOOTER_DATA',
  GET_FOOTER_DATA_SUCCESS: 'GET_FOOTER_DATA_SUCCESS',
  GET_TITLE_PAGE_DATA: 'GET_TITLE_PAGE_DATA',
  GET_TITLE_PAGE_DATA_SUCCESS: 'GET_TITLE_PAGE_DATA_SUCCESS',
  GET_SERVICES_SCROLLER_DATA: 'GET_SERVICES_SCROLLER_DATA',
  GET_SERVICES_SCROLLER_DATA_SUCCESS: 'GET_SERVICES_SCROLLER_DATA_SUCCESS',
  GET_PROFILES: 'GET_PROFILES',
  GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS'
}
