export const actionTypes = {
  SET_LANG: 'SET_LANG',
  GET_SETTINGS: 'GET_SETTINGS',
  GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
  GET_TITLE_PAGE_DATA: 'GET_TITLE_PAGE_DATA',
  GET_TITLE_PAGE_DATA_SUCCESS: 'GET_TITLE_PAGE_DATA_SUCCESS',
  GET_SERVICES_SCROLLER_DATA: 'GET_SERVICES_SCROLLER_DATA',
  GET_SERVICES_SCROLLER_DATA_SUCCESS: 'GET_SERVICES_SCROLLER_DATA_SUCCESS',
  GET_PROFILES: 'GET_PROFILES',
  GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
  GET_HOME: 'GET_HOME',
  GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
  GET_ABOUT_PAGE: 'GET_ABOUT_PAGE',
  GET_ABOUT_PAGE_SUCCESS: 'GET_ABOUT_PAGE_SUCCESS'
}
